language: node_js
node_js:
  - "0.10"

install:
  - npm install -g gulp mocha
  - npm install

script:
  - npm test

cache:
  directories:
  - node_modules

branches:
  only:
    - develop
    - master