language: node_js
node_js:
  - "0.10"

install:
  - npm install -g gulp mocha browserstack-runner
  - npm install codecov

script:
  - npm test
  - browserstack-runner

cache:
  directories:
  - node_modules

branches:
  only:
    - develop
    - master